import type { Metadata } from "next";
import "./globals.css";
import { Inclusive_Sans } from 'next/font/google'
import Header from "@/components/Header";

const inclusive_sans = Inclusive_Sans({
  weight: ["400"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Wint Khant Lin - Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inclusive_sans.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
