import type { Metadata } from "next";
import "./globals.css";
import { Inclusive_Sans } from 'next/font/google'
import Header from "@/components/Header";
import Script from "next/script";

const inclusive_sans = Inclusive_Sans({
  weight: ["400"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Wint Khant Lin - Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inclusive_sans.className} antialiased`}>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-QJ7KVTTN9F"
          strategy="worker"
        />
        <Header />
        <Script id="load-gtag" type={"text/partytown"} dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){window.dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-QJ7KVTTN9F');
          `,
        }} strategy="worker"></Script>
        {children}
      </body>
    </html>
  );
}
