import type { Metadata } from "next";
import "./globals.css";
import { Inclusive_Sans } from "next/font/google";
import Header from "@/components/Header";
import Script from "next/script";
import { Partytown } from "@qwik.dev/partytown/react";

const inclusive_sans = Inclusive_Sans({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wint Khant Lin - Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Partytown lib="/~partytown/" forward={["dataLayer.push"]} />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <Script
          id="google-analytics"
          type="text/partytown"
          strategy="worker"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              window.gtag = function gtag(){dataLayer.push(arguments);}
              
              window.gtag('js', new Date());

              window.gtag('config', 'G-QJ7KVTTN9F', {
                page_path: window.location.pathname,
                page_title: document.title,
                page_location: window.location.href,
                send_page_view: true,
                anonymize_ip: true
              });
            `,
          }}
        />
        <Script
          strategy="worker"
          async
          src={`https://www.googletagmanager.com/gtag/js?id=G-QJ7KVTTN9F`}
        />
        <script
          id="partytown-config"
          type="text/partytown"
          data-partytown-config
          dangerouslySetInnerHTML={{
            __html: `
              partytown = {
                lib: "/_next/static/~partytown/",
                forward: ["gtag"]
              };
            `,
          }}
        />
      </head>
      <body className={`${inclusive_sans.className} antialiased`}>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-QJ7KVTTN9F"
          strategy="worker"
        />
        <Header />
        {children}
      </body>
    </html>
  );
}
