name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: du -hs .next