name: "Build Next And Check Size"

on:
  push:
    branches:
      - dev

jobs:
  build-next-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: yarn
      - run: yarn build > log.txt
      - run: du -h .next

      - name: Comment on Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;

            const fs = require('fs');
            const buildLog = fs.readFileSync('log.txt', 'utf-8');

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: 'Build Log:\n```\n' + buildLog + '\n```',
            });
